configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://Mark:k1X6cQiKLRhb@ep-jolly-fog-a57ybqyf.us-east-2.aws.neon.tech/neondb?sslmode=require
  - configuration:
      name: twelvedata
      Authorization: apikey 68f03186d4434f17b7205a19cd848e41
